project_id = "syhqhdyvyahutymbzllg"

[functions.ai-grading]
verify_jwt = true

[functions.crop-health-prediction]
verify_jwt = true

[functions.route-optimization]
verify_jwt = true

[functions.esg-scoring]
verify_jwt = true

[functions.farmer-management]
verify_jwt = true

[functions.procurement-management]
verify_jwt = true

[functions.logistics-tracking]
verify_jwt = true

[functions.inventory-management]
verify_jwt = true

[functions.compliance-reporting]
verify_jwt = true

[functions.mqtt-handler]
verify_jwt = true

[functions.logistics-ai-optimization]
verify_jwt = true

[functions.logistics-batch-assign]
verify_jwt = true

[functions.logistics-track-update]
verify_jwt = true

[functions.logistics-batch-status]
verify_jwt = true

[functions.erp-integration]
verify_jwt = false

[functions.erp-callback]
verify_jwt = false

[functions.erp-delivery-status]
verify_jwt = false

[functions.registration-approval]
verify_jwt = true

[functions.submit-government-report]
verify_jwt = true

[functions.generate-compliance-report]
verify_jwt = true

[functions.analyze-feedback]
verify_jwt = true

[functions.vehicle-ai-insights]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.dispatcher-summary]
verify_jwt = true

[functions.driver-ai-assistant]
verify_jwt = true

[functions.dispatcher-assistant-token]
verify_jwt = true

[functions.dispatcher-assistant-text]
verify_jwt = true

[functions.serialization-management]
verify_jwt = true

[functions.compliance-sync]
verify_jwt = true
