project_id = "syhqhdyvyahutymbzllg"

[functions.ai-grading]
verify_jwt = false

[functions.crop-health-prediction]
verify_jwt = false

[functions.route-optimization]
verify_jwt = false

[functions.esg-scoring]
verify_jwt = false

[functions.farmer-management]
verify_jwt = false

[functions.procurement-management]
verify_jwt = false

[functions.logistics-tracking]
verify_jwt = false

[functions.inventory-management]
verify_jwt = false

[functions.compliance-reporting]
verify_jwt = false

[functions.mqtt-handler]
verify_jwt = false